spring:
  application.name: Employee Management

  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: sa
    driverClassName: org.h2.Driver
  jpa:
    database: h2

  h2:
    console:
      enabled: true
      path: /h2

  mail:
    host: smtp.mailgun.org
    port: 587
    username: ${SPRING_MAIL_USERNAME}  # From environment variables or your secret management
    password: ${SPRING_MAIL_PASSWORD}  # From environment variables or your secret management
    default-encoding: UTF-8
    test-connection: false
    properties:
      mail:
        smtp:
          auth: true
          starttls.enable: true

  cloud:
    circuitbreaker:
      resilience4j:
        enabled: true
        instances:
          mailgun-service:
            failureRateThreshold: 50
            slidingWindowSize: 100
            waitDurationInOpenState: 5000ms
            minimumNumberOfCalls: 10   # Minimum number of calls before calculating failure rate

springdoc:
  swagger-ui:
    path: /swagger-ui.html
  api-docs:
    path: /api-docs

app:
  mail-validation:
    config:
      apiKey: ${APP_MAIL_VALIDATION_CONFIG_API_KEY}

  mail:
    from: Rawafed Employee Management

